source 'https://rubygems.org'
ruby "2.5.1"

gem 'sinatra'
gem 'mongoid'
gem 'pry-byebug'
gem 'rack'
gem 'rake'
gem 'byebug'
gem 'rack-test'
gem 'pg'
gem 'time_difference'
gem 'mongoid_search'
gem 'sinatra-cors'
gem 'redis'
gem 'unicorn'
gem 'bunny'
gem 'connection_pool'
