development:
  clients:
    default:
      uri: <%= ENV["MONGOURL"] %>
      # database: nanotwitter
      # hosts:
      #   - ds153015.mlab.com:53015/nanotwitter
      # options:
      #   user: <%= ENV["MONGOUSER"] %>
      #   password: <%= ENV["MONGOPASS"] %>

production:
  clients:
    default:
      uri: <%= ENV["MONGOURL"] %>
      # database: nanotwitter
      # hosts:
      #   - ds153015.mlab.com:53015/nanotwitter
      # options:
      #   user: <%= ENV["MONGOUSER"] %>
      #   password: <%= ENV["MONGOPASS"] %>
